TDLMigration/Models/Category.cs
using System.Collections.Generic;

namespace TDLMigration.Models
{
  public class Category
    {
        public Category()
        {
            this.ItemsList = new HashSet<CategoryItem>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public virtual ICollection<CategoryItem> ItemsList { get; set; }
    }
}

TDLMigration/Models/CategoryItem.cs
namespace TDLMigration.Models
{
  public class CategoryItem
    {       
        public int CategoryItemId { get; set; }
        public int ItemId { get; set; }
        public int CategoryId { get; set; }
        public Item Item { get; set; }
        public Category Category { get; set; }
    }
}

TDLMigration/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace TDLMigration.Models
{
  public class TDLMigrationContextFactory : IDesignTimeDbContextFactory<TDLMigrationContext>
  {

    TDLMigrationContext IDesignTimeDbContextFactory<TDLMigrationContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<TDLMigrationContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new TDLMigrationContext(builder.Options);
    }
  }
}

TDLMigration/Models/Item.cs
using System.Collections.Generic;

namespace TDLMigration.Models
{
    public class Item
    {
        public int ItemId { get; set; }
        public string ItemDescription { get; set; }
        public ICollection<CategoryItem> CategoriesList { get;}
        
        public Item()
        {
            this.CategoriesList = new HashSet<CategoryItem>();
        }

     
    }
}

TDLMigration/Models/TDLMigrationContext.cs
using Microsoft.EntityFrameworkCore;

namespace TDLMigration.Models
{
  public class TDLMigrationContext : DbContext
  {
    public virtual DbSet<Category> CategoriesTable { get; set; }
    public DbSet<Item> ItemsTable { get; set; }
    public DbSet<CategoryItem> CategoryItemJoinedTable { get; set; }

    public TDLMigrationContext(DbContextOptions options) : base(options) { }
  }
}

TDLMigration/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using TDLMigration.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace TDLMigration.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly TDLMigrationContext _db;

        public CategoriesController(TDLMigrationContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Category> model = _db.CategoriesTable.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            _db.CategoriesTable.Add(category);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisCategory = _db.CategoriesTable
                .Include(category => category.ItemsList)
                .ThenInclude(join => join.Item)
                .FirstOrDefault(category => category.CategoryId == id);
            return View(thisCategory);
        }

        public ActionResult Edit(int id)
        {
            var thisCategory = _db.CategoriesTable.FirstOrDefault(category => category.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            _db.Entry(category).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisCategory = _db.CategoriesTable.FirstOrDefault(category => category.CategoryId == id);
            return View(thisCategory);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisCategory = _db.CategoriesTable.FirstOrDefault(category => category.CategoryId == id);
            _db.CategoriesTable.Remove(thisCategory);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TDLMigration/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

TDLMigration/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using TDLMigration.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TDLMigration.Controllers
{
    public class ItemsController : Controller
    {
        private readonly TDLMigrationContext _db;

        public ItemsController(TDLMigrationContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.ItemsTable.ToList());
        }

        public ActionResult Details(int id)
        {
            var thisItem = _db.ItemsTable
                .Include(item => item.CategoriesList)
                .ThenInclude(join => join.Category)
                .FirstOrDefault(item => item.ItemId == id);
            return View(thisItem);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_db.CategoriesTable, "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item item, int CategoryId)
        {
            _db.ItemsTable.Add(item);
            if (CategoryId != 0)
            {
                _db.CategoryItemJoinedTable.Add(new CategoryItem() { CategoryId = CategoryId, ItemId = item.ItemId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var thisItem = _db.ItemsTable.FirstOrDefault(items => items.ItemId == id);
            ViewBag.CategoryId = new SelectList(_db.CategoriesTable, "CategoryId", "Name");
            return View(thisItem);
        }

        [HttpPost]
        public ActionResult Edit(Item item, int CategoryId)
        {
            if (CategoryId != 0)
            {
                _db.CategoryItemJoinedTable.Add(new CategoryItem() { CategoryId = CategoryId, ItemId = item.ItemId });
            }
            _db.Entry(item).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddCategory(int id)
        {
            var thisItem = _db.ItemsTable.FirstOrDefault(items => items.ItemId == id);
            ViewBag.CategoryId = new SelectList(_db.CategoriesTable, "CategoryId", "Name");
            return View(thisItem);
        }

        [HttpPost]
        public ActionResult AddCategory(Item item, int CategoryId)
        {
            if (CategoryId != 0)
            {
                _db.CategoryItemJoinedTable.Add(new CategoryItem() { CategoryId = CategoryId, ItemId = item.ItemId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisItem = _db.ItemsTable.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisItem = _db.ItemsTable.FirstOrDefault(items => items.ItemId == id);
            _db.ItemsTable.Remove(thisItem);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteCategory(int joinId)
        {
            var joinEntry = _db.CategoryItemJoinedTable.FirstOrDefault(entry => entry.CategoryItemId == joinId);
            _db.CategoryItemJoinedTable.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

TDLMigration/Views/Categories/Create.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Category

<h4>Add a new category</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.CategoryName)
    @Html.TextBoxFor(model => model.CategoryName)
    <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>

TDLMigration/Views/Categories/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Category

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.CategoryName): @Html.DisplayFor(model => model.CategoryName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to categories", "Index")

TDLMigration/Views/Categories/Details.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Category;

<h2>Category Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.CategoryName): @Html.DisplayFor(model => model.CategoryName)</h3>

@if(@Model.ItemsList.Count == 0)
{
  <p>This category does not contain any items</p>
}
else
{
  <h4>Items the category contains:</h4>
  <ul>
  @foreach(var join in Model.ItemsList)
  {
    <li>@join.Item.ItemDescription</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to categories", "Index")</p>
<p>@Html.ActionLink("Edit Category", "Edit", new { id = Model.CategoryId })</p>
<p>@Html.ActionLink("Delete Category", "Delete", new { id = Model.CategoryId })</p>

TDLMigration/Views/Categories/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Category

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.CategoryName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CategoryId)

    @Html.LabelFor(model => model.CategoryName)
    @Html.EditorFor(model => model.CategoryName)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to categories", "Index")</p>

TDLMigration/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1 style="text-align: center;">Welcome to the To Do List!</h1>
<h1 style="text-align: center;">You at least made it to the homepage!</h1>
<h3 style="text-align: center;">Congratulations!</h3>

@* I am link to to the Index method on the ItemsController. *@

<p>@Html.ActionLink("See all items", "Index", "Items")</p>
<p>@Html.ActionLink("See all categories", "Index", "Categories")</p>

TDLMigration/Views/Items/AddCategory.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Item

<h2>Add a category</h2>

<h4>Add a category to this task: @Html.DisplayFor(model => model.ItemDescription)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ItemId)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TDLMigration/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Item

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.ItemDescription)
    @Html.TextBoxFor(model => model.ItemDescription)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Add new item" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all items", "Index")</p>

TDLMigration/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Item

<h2>Are you sure you want to delete this Item?</h2>

@Html.DisplayNameFor(model => model.ItemDescription): @Html.DisplayFor(model => model.ItemDescription)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

TDLMigration/Views/Items/Details.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Item

<h2>Item Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.ItemDescription): @Html.DisplayFor(model => model.ItemDescription)</h3>

@if(@Model.CategoriesList.Count == 0)
{
  <p>This item does not belong to any categories</p>
}
else
{
  <h4>Categories the item belongs to:</h4>
  <ul>
  @foreach(var join in Model.CategoriesList)
  {
    <li>@join.Category.CategoryName</li>
  }
  </ul>
}

 <ul>
  @foreach(var join in Model.CategoriesList)
  {
    <li>@join.Category.CategoryName</li>
    @using (Html.BeginForm("DeleteCategory", "Items"))
    {
      @Html.Hidden("joinId", @join.CategoryItemId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>

<p>@Html.ActionLink("Add a Category", "AddCategory", new { id = Model.ItemId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.ItemId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.ItemId })</p>

TDLMigration/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TDLMigration.Models.Item

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.ItemDescription)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ItemId)

    @Html.LabelFor(model => model.ItemDescription)
    @Html.EditorFor(model => model.ItemDescription)

    @Html.Label("Select category")
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TDLMigration/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}

@using TDLMigration.Models;
@model List<TDLMigration.Models.Item>;

<h1>Items</h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
}

@foreach (Item item in @Model)
{
  <li>@Html.ActionLink($"{item.ItemDescription}", "Details", new { id = item.ItemId })</li>
}

<p>@Html.ActionLink("Add new item", "Create")</p>
<p>@Html.ActionLink("Add new category", "Create", "Categories")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TDLMigration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Claire's Salon</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700&display=swap" rel="stylesheet">
    <link rel='stylesheet' href='~/css/styles.css'>
  </head>
  <body>

    <div class="container body-container">
      @RenderBody()
    </div> 

  </body>
</html>